Repository DeveloperAcademy-POSTECH/2024-MC3-M17-TeamMosuChalamet-iOS, pull requests merged in 2024-08, with the labels that each got.

#48 [Feat] Assets 및 AppIcon 추가
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/1024.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/1024x768@1x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/27x20@2x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/27x20@3x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/32x24@2x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/32x24@3x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/58 1.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/58.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/60x45@2x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/60x45@3x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/67x50@2x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/74x55@2x.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/87.png
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/Contents.json
  Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift
  Shoak/Actors/CommonActor/View/LoginView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/DesignSystem/Assets.xcassets/AppIcon.appiconset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/AppIcon.appiconset/ShoakIcon.png
  Shoak/DesignSystem/Assets.xcassets/ShoakHandGestureIcon.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/ShoakHandGestureIcon.imageset/ShoakHandGestureIcon@1x.png
  Shoak/DesignSystem/Assets.xcassets/ShoakHandGestureIcon.imageset/ShoakHandGestureIcon@2x.png
  Shoak/DesignSystem/Assets.xcassets/ShoakHandGestureIcon.imageset/ShoakHandGestureIcon@3x.png
  Shoak/DesignSystem/Assets.xcassets/ShoakIcon.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/ShoakIcon.imageset/ShoakIcon.png
  Shoak/DesignSystem/Assets.xcassets/ShoakIcon.imageset/ShoakIcon@2x.png
  Shoak/DesignSystem/Assets.xcassets/ShoakIcon.imageset/ShoakIcon@3x.png
  ShoakWatch Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ShoakWatch Watch App/Assets.xcassets/AppIcon.appiconset/ShoakIcon.png
  ShoakWatch Watch App/Assets.xcassets/AppIcon.appiconset/shaokicon.png
Labels: Feat

#47 [Feat] 페이로드 알림 확인
  Shoak.xcodeproj/project.pbxproj
  ShoakWatch Watch App/ShoakWatchApp.swift
  ShoakWatch Watch App/View/NotificationService.swift
  ShoakWatch Watch App/View/PushNotificationPayload.apns
  ShoakWatch Watch App/View/WatchNotificationController.swift
  ShoakWatch Watch App/View/WatchNotificationView.swift
Labels: Feat

#51 [Feat] 프로필 기본 이미지 넣기 & refreshProfile() 구현
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/InvitationActor/View/InviteFriendsView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/AccountManager.swift
  Shoak/DesignSystem/Assets.xcassets/defaultProfile.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/defaultProfile.imageset/defaultProfile@1x.png
  Shoak/DesignSystem/Assets.xcassets/defaultProfile.imageset/defaultProfile@2x.png
  Shoak/DesignSystem/Assets.xcassets/defaultProfile.imageset/defaultProfile@3x.png
Labels: Feat

#54 [Feat] Watch에서도 shoak 보내지게 설정
  Shoak.xcodeproj/project.pbxproj
  Shoak/Common/WatchConnectivityManager.swift
  Shoak/Network/Token/TokenManager.swift
  Shoak/ShoakApp.swift
  ShoakWatch Watch App/PhoneConnectivityManager.swift
  ShoakWatch Watch App/ShoakWatchApp.swift
  ShoakWatch Watch App/View/ContentView.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
Labels: Feat

#56 [#55] Watch 사용성 개선
  Shoak/Common/ShoakDataManager.swift
  ShoakWatch Watch App/ShoakWatchApp.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
Labels: Fix

#62 [Feat] 인앱 알림, shortcut 온보딩 설정
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/ShoakActor/View/OnboardingView.swift
  Shoak/Common/Intents/StartShoakProcess.swift
  Shoak/Common/Intents/StartShoakShortcuts.swift
  Shoak/Common/쇽 시작하기.shortcut
  Shoak/DesignSystem/Assets.xcassets/ShoakLogoFilled.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/ShoakLogoFilled.imageset/ShoakLogoFilled.png
  Shoak/ShoakApp.swift
  Shoak/ShoakAppDelegate.swift
Labels: Feat

#61 [Fix] 쇽 버튼 로직 수정
  Shoak/Actors/ShoakActor/View/FriendListView.swift
Labels: Fix

#65 [Feat] 친구 초대 로직 완료
  InviteFriends/Assets.xcassets/ShoakLogoFilled.imageset/Contents.json
  InviteFriends/Assets.xcassets/ShoakLogoFilled.imageset/ShoakLogoFilled.png
  InviteFriends/Base.lproj/MainInterface.storyboard
  InviteFriends/InvitationViewController.swift
  InviteFriends/MessagesViewController.swift
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/AppleAdminActor/View/MessageComposeView.swift
  Shoak/Actors/CommonActor/UseCases/AuthUseCase.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/InvitationActor/UseCases/InvitationUseCase.swift
  Shoak/Actors/InvitationActor/View/AcceptInvitationView.swift
  Shoak/Actors/InvitationActor/View/InviteFriendsView.swift
  Shoak/Actors/ShoakActor/UseCases/UserUseCase.swift
  Shoak/Actors/ShoakActor/View/DeleteFriendView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Common/InvitationManager.swift
  Shoak/Common/NavigationManager.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Entity/TMMemberID.swift
  Shoak/Entity/TMProfileDTO.swift
  Shoak/Entity/TMProfileVO.swift
  Shoak/Network/API/InvitationAPI.swift
  Shoak/Network/API/UserAPI.swift
  Shoak/Network/Repository/InvitationRepository.swift
  Shoak/Network/Repository/UserRepository.swift
  Shoak/Network/Token/TokenManager.swift
  Shoak/ShoakApp.swift
  Shoak/ShoakAppDelegate.swift
  Shoak/Utility/Int64+.swift
  Shoak/Utility/String+Int64.swift
  Shoak/Utility/TargetType+.swift
  Shoak/Utility/ViewModifiers/AddEnvorinmentsForPreview.swift
  ShoakWatch Watch App/PhoneConnectivityManager.swift
  ShoakWatch Watch App/ShoakWatchApp.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
  ShoakWatch Watch App/View/WatchNotificationController.swift
  ShoakWatch Watch App/View/WatchNotificationView.swift
Labels: Feat

#67 [Feat] 프로필 사진 수정 구현
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/View/EditProfileView.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Common/NavigationManager.swift
  Shoak/Entity/TMMemberID.swift
  Shoak/Info.plist
Labels: Feat

#70 [Fix] 친구삭제 UI 세부사항 수정
  Shoak/Actors/ShoakActor/View/DeleteFriendView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
Labels: Fix

#71 [Fix] 디바이스 토큰 갱신
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/View/EditProfileView.swift
  Shoak/Entity/TMDeviceTokenDTO.swift
  Shoak/Network/API/TokenRefreshAPI.swift
  Shoak/Network/APIClient.swift
  Shoak/Network/MoyaPlugins/AddTokenPlugin.swift
  Shoak/Network/Repository/TokenRefreshRepository.swift
  Shoak/Network/Token/TokenManager.swift
Labels: Fix

#76 [Fix] AsyncImage 에러 해결
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/ShoakActor/UseCases/SendShoakUseCase.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Info.plist
  ShoakWatch Watch App/View/WatchFriendListView.swift
Labels: Fix

#78 [Fix] 햅틱 수정
  ShoakWatch Watch App/View/WatchNotificationController.swift
Labels: Fix

#80 [Feat] 회원탈퇴 Alert 구현 및 앨범 이미지 비동기처리(+화질 개선)
  Shoak/Actors/CommonActor/View/EditProfileView.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
Labels: Feat, Fix

#82 [Fix 겸 Feat] Lottie 추가 및 친구 초대 QR 추가
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/InvitationActor/View/InviteFriendsView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/DesignSystem/Check.json
  Shoak/Utility/HapticManager.swift
  Shoak/Utility/ViewModifiers/ButtonStyles.swift
Labels: Feat, Fix

#87 [Fix] 온보딩 UI 수정
  Shoak/Actors/ShoakActor/View/OnboardingView.swift
  Shoak/DesignSystem/Assets.xcassets/AppIcon.appiconset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/AppIcon.appiconset/ShoakAppIcon.png
  Shoak/DesignSystem/Assets.xcassets/AppIcon.appiconset/ShoakIcon.png
  Shoak/DesignSystem/Assets.xcassets/Ob1.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob1.imageset/Ob1.png
  Shoak/DesignSystem/Assets.xcassets/Ob2.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob2.imageset/Ob2.png
  Shoak/DesignSystem/Assets.xcassets/Ob3.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob3.imageset/Ob3.png
  Shoak/DesignSystem/Assets.xcassets/Ob4.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob4.imageset/Ob4.png
  Shoak/DesignSystem/Assets.xcassets/Ob5.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob5.imageset/Ob5.png
  Shoak/DesignSystem/Assets.xcassets/Ob6.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob6.imageset/Ob6.png
  Shoak/DesignSystem/Assets.xcassets/Ob7.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Ob7.imageset/Ob7.png
  Shoak/DesignSystem/Assets.xcassets/shortcut.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/shortcut.imageset/shortcut@1x.png
  Shoak/DesignSystem/Assets.xcassets/shortcut.imageset/shortcut@2x.png
  Shoak/DesignSystem/Assets.xcassets/shortcut.imageset/shortcut@3x.png
  Shoak/DesignSystem/Assets.xcassets/watch.imageset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/watch.imageset/watch.svg
Labels: Fix

#93 [Fix] Lottie 아이콘 앱클립에서 안보이는 오류 수정, 이름 수정 추가
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/ShoakActor/UseCases/UserUseCase.swift
  Shoak/Common/AccountManager.swift
  Shoak/Entity/TMNameDTO.swift
  Shoak/Network/API/UserAPI.swift
  Shoak/Network/Repository/UserRepository.swift
  ShoakTests/AuthUseCaseTests.swift
  ShoakTests/TokenManagerTests.swift
Labels: Fix

#96 [Doc] README.md 수정
  README.md
Labels: Doc

#95 [#94] 온보딩에 프로필 수정 추가
  Shoak/Actors/CommonActor/View/Components/BackButton.swift
  Shoak/Actors/CommonActor/View/EditProfileView.swift
  Shoak/Actors/CommonActor/View/LoginView.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/InvitationActor/View/InviteFriendsView.swift
  Shoak/Actors/ShoakActor/View/DeleteFriendView.swift
  Shoak/Actors/ShoakActor/View/OnboardingView.swift
  Shoak/Common/NavigationManager.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Network/Token/TokenRepository.swift
  ShoakWatch Watch App/PhoneConnectivityManager.swift
  ShoakWatch Watch App/ShoakWatchApp.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
Labels: Feat

#97 [ Fix] 이름 8글자 제한 guard문 고치기
  Shoak/Actors/CommonActor/View/SettingView.swift
Labels: Fix

#99 [Fix] 각종 오류 개선
  Shoak/Actors/CommonActor/View/EditProfileView.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/InvitationActor/View/AcceptInvitationView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
Labels: Fix

#101 [Fix] 디바이스 토큰 로직 및 로그인 로직 점검
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Common/NavigationManager.swift
  Shoak/Info.plist
  Shoak/Network/APIClient.swift
  Shoak/Network/MoyaPlugins/AddTokenPlugin.swift
  Shoak/Network/MoyaPlugins/LogoutPlugin.swift
  Shoak/Network/MoyaPlugins/StoreTokenPlugin.swift
  Shoak/Network/Repository/TokenRefreshRepository.swift
  Shoak/Network/RequestInterceptor.swift
  Shoak/Network/Token/TokenStorage.swift
  Shoak/ShoakAppDelegate.swift
  Shoak/Utility/Notification.Name+.swift
  ShoakClip/Info.plist
  ShoakTests/TokenManagerTests.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
Labels: Fix

#104 [Fix] 이름 변경 시 버튼 disable 로직 추가
  Shoak/Actors/CommonActor/View/SettingView.swift
Labels: Fix

#106 [Refactor] 프로필 수정 앨범 방식 변경
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/View/Components/ImagePicker.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
Labels: Refactor

#108 [ Fix] 딥링크 처리 과정에서 이전에 처리한 딥링크는 다시 인식하지 않도록 변경, 로그인 시 디바이스 토큰 갱신 기다리기, 토큰 갱신 실패 시 401이 떠도 로그아웃 하도록 변경
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Network/API/UserAPI.swift
  Shoak/Network/MoyaPlugins/LogoutPlugin.swift
  Shoak/ShoakApp.swift
  ShoakClip/ShoakClipApp.swift
Labels: Fix
