Repository DeveloperAcademy-POSTECH/2024-MC3-M17-TeamMosuChalamet-iOS, pull requests merged in 2024-07, with the labels that each got.

#3 [#2] TMProfile DTO, VO, 나머지 Sample 추가
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/AppleAdminActor/UseCases/SampleUseCase4.swift
  Shoak/Actors/AppleAdminActor/View/SwiftUIView4.swift
  Shoak/Actors/CommonActor/UseCases/SampleUseCase3.swift
  Shoak/Actors/CommonActor/View/SwiftUIView3.swift
  Shoak/Actors/InvitationActor/UseCases/SampleUseCase2.swift
  Shoak/Actors/InvitationActor/View/SwiftUIView2.swift
  Shoak/Actors/ShoakActor/UseCases/ShoakUseCase.swift
  Shoak/Entity/TMMemberID.swift
  Shoak/Entity/TMProfileDTO.swift
  Shoak/Entity/TMProfileVO.swift
  Shoak/ShoakApp.swift
  Shoak/Utility/Sample.swift
  SwiftUIView.swift
Labels: Feat

#5 [fix] TMProfileDTO, TMProfileVO 수정
  Shoak/Actors/ShoakActor/UseCases/ShoakUseCase.swift
  Shoak/Entity/TMProfileDTO.swift
  Shoak/Entity/TMProfileVO.swift
  SwiftUIView.swift
Labels: Fix

#7 [Feat] Sign in with Apple 구현
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/AppleAdminActor/UseCases/SampleUseCase4.swift
  Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift
  Shoak/Actors/AppleAdminActor/View/Components/AppleSignInButton.swift
  Shoak/Actors/AppleAdminActor/View/SwiftUIView4.swift
  Shoak/Shoak.entitlements
  Shoak/ShoakApp.swift
Labels: Feat

#10 [feat] 빌드 오류 해결
  Shoak.xcodeproj/project.pbxproj
Labels: Feat

#12 [Fix] 누락 파일 정리 및 이슈 템플릿 조금 더 생성
  .github/ISSUE_TEMPLATE/1-New Feature.yml
  .github/ISSUE_TEMPLATE/2-Fix.yml
  .github/ISSUE_TEMPLATE/3-Refactor.yml
  .github/ISSUE_TEMPLATE/4-Doc.yml
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/ShoakActor/View/FriendListView.swift
Labels: Fix

#14 [Feat] Navigation Manager, Account Manager 개선, Onbarding 플로우 정의
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/UseCases/AccountUseCase.swift
  Shoak/Actors/CommonActor/View/LoginView.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Actors/ShoakActor/View/OnboardingView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Common/Intents/StartShoakProcess.swift
  Shoak/Common/NavigationManager.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/RootView.swift
  Shoak/ShoakApp.swift
  ShoakWatch Watch App/ShoakWatchApp.swift
  ShoakWatch Watch App/View/ContentView.swift
  ShoakWatch Watch App/View/WatchFriendListView.swift
  ShoakWatch Watch App/View/WatchSettingView.swift
Labels: Feat

#16 [feat] 유저 유스케이스 서버 연결 및 테스트 코드 추가
  Shoak.xcodeproj/project.pbxproj
  Shoak.xcodeproj/xcshareddata/xcschemes/Shoak.xcscheme
  Shoak.xcodeproj/xcshareddata/xcschemes/ShoakTests.xcscheme
  Shoak.xcodeproj/xcshareddata/xcschemes/ShoakWatch Watch App.xcscheme
  Shoak/Actors/CommonActor/UseCases/AccountUseCase.swift
  Shoak/Actors/ShoakActor/UseCases/UserUseCase.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Entity/TMFriendDTO.swift
  Shoak/Entity/TMFriendVO.swift
  Shoak/Entity/TMMemberID.swift
  Shoak/Entity/TMProfileDTO.swift
  Shoak/Entity/TMProfileVO.swift
  Shoak/Info.plist
  Shoak/Network/API/UserAPI.swift
  Shoak/Network/DefaultAPIClient.swift
  Shoak/Network/NetworkError.swift
  Shoak/Network/NetworkHandler.swift
  Shoak/Network/Repository/UserRepository.swift
  Shoak/Network/URLProvider.swift
  Shoak/Utility/MoyaProvider+.swift
  Shoak/Utility/TargetType+.swift
  ShoakTests/UserUseCaseTests.swift
  ShoakWatch-Watch-App-Info.plist
Labels: Feat

#18 [Feat] 프로필 이미지 업로드 유스케이스 추가
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/ShoakActor/UseCases/UserUseCase.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Network/API/UserAPI.swift
  Shoak/Network/Repository/UserRepository.swift
  Shoak/Utility/TargetType+.swift
  ShoakTests/TestAssets.xcassets/Contents.json
  ShoakTests/TestAssets.xcassets/Vinci.imageset/Contents.json
  ShoakTests/TestAssets.xcassets/Vinci.imageset/Vinci.jpeg
  ShoakTests/UserUseCaseTests.swift
Labels: Feat

#20 [Feat] iMessage 구현
  InviteFriends/Assets.xcassets/Contents.json
  InviteFriends/Assets.xcassets/iMessage App Icon.stickersiconset/Contents.json
  InviteFriends/Base.lproj/MainInterface.storyboard
  InviteFriends/Info.plist
  InviteFriends/MessagesViewController.swift
  Shoak.xcodeproj/project.pbxproj
  Shoak.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Shoak.xcodeproj/xcshareddata/xcschemes/InviteFriends.xcscheme
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift
  Shoak/Actors/AppleAdminActor/View/MessageComposeView.swift
  Shoak/Shoak.entitlements
Labels: Feat

#25 [Feat] 친구 추가 Message UI 구현중
  InviteFriends/Base.lproj/MainInterface.storyboard
  InviteFriends/MessagesViewController.swift
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift
  Shoak/Actors/AppleAdminActor/View/MessageComposeView.swift
  Shoak/Actors/CommonActor/View/LoginView.swift
  Shoak/Actors/InvitationActor/UseCases/InvitationUseCase.swift
  Shoak/Actors/InvitationActor/UseCases/SampleUseCase2.swift
  Shoak/Actors/InvitationActor/View/InviteFriendsView.swift
  Shoak/Actors/InvitationActor/View/SwiftUIView2.swift
  Shoak/Common/InvitationManager.swift
  Shoak/Common/NavigationManager.swift
  Shoak/DesignSystem/Assets.xcassets/AccentColor.colorset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/AppIcon.appiconset/Contents.json
  Shoak/DesignSystem/Assets.xcassets/Contents.json
  Shoak/DesignSystem/Color/ColorManager.swift
  Shoak/DesignSystem/Font/FontManager.swift
  Shoak/ShoakApp.swift
Labels: Feat

#27 [Feat] Login 로직 구성중
  Shoak.xcodeproj/project.pbxproj
  Shoak.xcodeproj/xcshareddata/xcschemes/InviteFriends.xcscheme
  Shoak.xcodeproj/xcshareddata/xcschemes/Shoak.xcscheme
  Shoak.xcodeproj/xcshareddata/xcschemes/ShoakWatch Watch App.xcscheme
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/CommonActor/UseCases/AuthUseCase.swift
  Shoak/Entity/TMLoginOrSignUpDTO.swift
  Shoak/Network/API/AuthAPI.swift
  Shoak/Network/API/TokenRefreshAPI.swift
  Shoak/Network/APIClient.swift
  Shoak/Network/DefaultAPIClient.swift
  Shoak/Network/MoyaPlugins/LoggerPlugin.swift
  Shoak/Network/MoyaPlugins/StoreTokenPlugin.swift
  Shoak/Network/MoyaPlugins/ValidateAndAddTokenPlugin.swift
  Shoak/Network/Repository/AuthRepository.swift
  Shoak/Network/Token/TokenManager.swift
  Shoak/Utility/Array+subscript.swift
  Shoak/Utility/Keychain.swift
  ShoakTests/AuthUseCaseTests.swift
  ShoakUITests/ShoakUITests.swift
  ShoakUITests/ShoakUITestsLaunchTests.swift
Labels: Feat

#29 [Refactor] NSLayoutConstraint 사용하기
  InviteFriends/MessagesViewController.swift
  Shoak.xcodeproj/project.pbxproj
Labels: Refactor

#31 [Feat] 친구 리스트 뷰
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/InvitationManager.swift
  Shoak/RootView.swift
  Shoak/ShoakApp.swift
  Shoak/Utility/ViewModifiers/AddEnvorinmentsForPreview.swift
  Shoak/Utility/ViewModifiers/ClipShapeBorder.swift
Labels: Feat

#33 [Feat] 로그인 플로우 & 디바이스 토큰 얻어오기
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/AppleAdminActor/View/AppleLoginView.swift
  Shoak/Actors/CommonActor/UseCases/AuthUseCase.swift
  Shoak/Actors/CommonActor/View/LoginView.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Actors/ShoakActor/View/OnboardingView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Entity/TMUserCredentialVO.swift
  Shoak/Shoak.entitlements
  Shoak/ShoakApp.swift
  Shoak/ShoakAppDelegate.swift
  ShoakTests/AuthUseCaseTests.swift
Labels: Feat

#37 [Feat] Onboarding 뷰, 백버튼
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/CommonActor/View/Components/BackButton.swift
  Shoak/Actors/ShoakActor/View/OnboardingView.swift
  Shoak/Utility/CaseIterable+.swift
Labels: Feat

#39 [Feat] 친구추가 화면 및 로직 관련 수정사항
  InviteFriends/MessagesViewController.swift
  Shoak/Actors/InvitationActor/View/InviteFriendsView.swift
Labels: Feat, Refactor

#42 [Feat] 로그인 API에 토큰 붙이는 로직 추가
  Shoak.xcodeproj/project.pbxproj
  Shoak/Actors/AppleAdminActor/UseCases/AppleUseCase.swift
  Shoak/Actors/CommonActor/UseCases/AuthUseCase.swift
  Shoak/Actors/CommonActor/View/LoginView.swift
  Shoak/Actors/CommonActor/View/SettingView.swift
  Shoak/Actors/ShoakActor/UseCases/SendShoakUseCase.swift
  Shoak/Actors/ShoakActor/View/FriendListView.swift
  Shoak/Common/AccountManager.swift
  Shoak/Common/ShoakDataManager.swift
  Shoak/Entity/TMLoginOrSignUpDTO.swift
  Shoak/Entity/TMShoakDestinationDTO.swift
  Shoak/Entity/TMTokenRefreshRequestDTO.swift
  Shoak/Network/API/AuthAPI.swift
  Shoak/Network/API/ShoakAPI.swift
  Shoak/Network/API/TokenRefreshAPI.swift
  Shoak/Network/API/UserAPI.swift
  Shoak/Network/APIClient.swift
  Shoak/Network/MoyaPlugins/LoggerPlugin.swift
  Shoak/Network/MoyaPlugins/StoreTokenPlugin.swift
  Shoak/Network/MoyaPlugins/TokenRefreshPlugin.swift
  Shoak/Network/MoyaPlugins/ValidateAndAddTokenPlugin.swift
  Shoak/Network/NetworkHandler.swift
  Shoak/Network/Repository/AuthRepository.swift
  Shoak/Network/Repository/ShoakRepository.swift
  Shoak/Network/Token/Token.swift
  Shoak/Network/Token/TokenManager.swift
  Shoak/Network/Token/TokenRefreshAPIService.swift
  Shoak/Network/Token/TokenStorage.swift
  Shoak/ShoakAppDelegate.swift
  Shoak/Utility/Keychain.swift
  Shoak/Utility/MoyaProvider+.swift
  Shoak/Utility/TargetType+.swift
  ShoakTests/TokenManagerTests.swift
Labels: Feat

#43 [Feat] 설정 UI 구현
  Shoak/Actors/CommonActor/View/SettingView.swift
Labels: Feat
